#!/usr/bin/env python
import subprocess

deploy_ip = "<DEV_SERVER>"

# Upload html to dev.stanfy.com
print "\033[92mSending configuration files ...\033[0m"
subprocess.call("chmod 600 pebble_key", shell=True)
pathToHtml = 'server/public/'
command = "rsync -vr " + pathToHtml + " -e 'ssh -p9322 -i pebble_key' pebble@" + deploy_ip + ":pebble-cal/"
subprocess.call(command, shell=True)
print
